#!/usr/bin/env bash
# 🚀 ابدأ الآن - Quick Start Guide (بسيط وسريع جداً)

echo "=================="
echo "🚀 BUILD A LIBRARY"
echo "=================="
echo ""
echo "⏱️  1️⃣  الخادم (Backend) - افتح Terminal الأول:"
echo "   cd server"
echo "   npm install   (أول مرة فقط)"
echo "   npm run dev"
echo ""
echo "⏱️  2️⃣  العميل (Frontend) - افتح Terminal الثاني:"
echo "   cd client/my-react-app"
echo "   npm install   (أول مرة فقط)"
echo "   npm run dev"
echo ""
echo "⏱️  3️⃣  افتح المتصفح:"
echo "   http://localhost:5173"
echo ""
echo "=================="
echo "✅ جاهز!"
echo "=================="
echo ""
echo "🔓 حسابات تجريبية (Test Accounts):"
echo "   Email: test@example.com"
echo "   Password: test123456"
echo ""
echo "👨‍💼 حساب مسؤول (Admin Account):"
echo "   Email: admin@example.com"
echo "   Password: admin123"
echo ""
echo "📚 ملفات مهمة:"
echo "   - README.md              (شرح شامل)"
echo "   - QUICK_START.txt        (دليل سريع)"
echo "   - FAQ_TROUBLESHOOTING.md (حل المشاكل)"
echo ""
echo "🎯 الميزات:"
echo "   ✅ تسجيل وتسجيل دخول"
echo "   ✅ إدارة كتب كاملة"
echo "   ✅ نظام أسئلة وأجوبة AI"
echo "   ✅ نظام المفضلة"
echo "   ✅ لوحة إدارة متقدمة"
echo ""
echo "🔧 Troubleshooting:"
echo "   1. هل Node.js و MySQL مثبتان؟ تحقق من اصداراتك"
echo "   2. هل المنفذ 3001 و 5173 متاحان?"
echo "   3. شغّل: node HEALTH_CHECK.js للفحص"
echo ""
echo "مستخدمون جدد؟ اقرأ QUICK_START.txt أو README.md"
echo ""
